version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mimic
    networks:
      - braille_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  mimic:
    image: mycroftai/mimic3
    ports:
      - "59125:59125"
    networks:
      - braille_network
    volumes:
      - mimic3_data:/home/mimic3/.local/share
    environment:
      - HOME=/home/mimic3
    user: "0:0"

networks:
  braille_network:
    driver: bridge

volumes:
  mimic3_data:
    driver: local
